parameters:
  jobName: 'WindowsEnvGen'
  dependency: 'Tests'
  vmImage: 'vs2017-win2016'
  pythonVersion: '3.6'
  artifactName: 'Windows'

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependency }}
  pool:
      vmImage: ${{ parameters.vmImage }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      addToPath: true
  - task: PowerShell@2
    inputs: 
      filePath: 'pack\scripts\win_deps.ps1'
  - task: CopyFiles@2
    inputs:
      contents: |
        azure\__init__.py
      targetFolder: '$(Build.ArtifactStagingDirectory)\deps\azure'
      flattenFolders: true
  - task: CopyFiles@2
    inputs:
      contents: |
        python\*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true  
  - task: CopyFiles@2
    inputs:
      contents: |
        deps\**\*
        !deps\grpc_tools\**\*
        !deps\grpcio_tools*\*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: ${{ parameters.artifactName }}