# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# E2E Integration Test Pipeline

pr: none
trigger: none

pool:
    vmImage: 'ubuntu-latest'

variables:
    DOTNET_VERSION: '3.1.x'
    DOTNET_VERSION_6: '6.x'
    PYTHON_VERSION: '3.9'

steps:
- task: UsePythonVersion@0
  displayName: 'Install Python'
  inputs:
    versionSpec: $(PYTHON_VERSION)
    addToPath: true
- task: UseDotNet@2
  displayName: 'Install DotNet 3'
  inputs:
    packageType: 'sdk'
    version: $(DOTNET_VERSION)
- task: UseDotNet@2
  displayName: 'Install DotNet 6'
  inputs:
    packageType: 'sdk'
    version: $(DOTNET_VERSION_6)
- pwsh: '$(Build.SourcesDirectory)/.ci/e2e_integration_test/start-e2e.ps1'
  env:
    AzureWebJobsStorage: $(AzureWebJobsStorage)
    AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
    AzureWebJobsEventHubConnectionString: $(AzureWebJobsEventHubConnectionString)
    AzureWebJobsServiceBusConnectionString: $(AzureWebJobsServiceBusConnectionString)
    AzureWebJobsSqlConnectionString: $(AzureWebJobsSqlConnectionString)
    AzureWebJobsEventGridTopicUri: $(AzureWebJobsEventGridTopicUri)
    AzureWebJobsEventGridConnectionKey: $(AzureWebJobsEventGridConnectionKey)
    PythonVersion: $(PYTHON_VERSION)
  displayName: 'Running Python Language Worker E2E Tests'
- task: PublishTestResults@2
  displayName: 'Publish Python Worker E2E Test Result'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'e2e-integration-test-report.xml'
    testRunTitle: 'Publish Python Worker E2E Test Result'
    failTaskOnFailedTests: true
