environment:
    global:
        PYAZURE_WEBHOST_PATH: "downloads\\webhost"
        PYAZURE_WEBHOST_EXECUTABLE: Microsoft.Azure.WebJobs.Script.WebHost.dll

    matrix:
        - PYTHON: "C:\\Python36-x64\\python.exe"

install:
    - ps: .ci\appveyor_download_webhost.ps1
    - "%PYTHON% -m pip install --upgrade pip wheel setuptools"

build_script:
    - "%PYTHON% -m pip install -U -e .[dev]"

test_script:
    - set PYAZURE_WEBHOST_DLL=%cd%\%PYAZURE_WEBHOST_PATH%\%PYAZURE_WEBHOST_EXECUTABLE% && %PYTHON% .ci\appveyor_setup_worker.py > worker_path && set /p PYAZURE_WORKER_DIR=<worker_path && %PYTHON% setup.py test
