codecov:
  branch: wangbill/pr-comment-codecov # set new Default branch

coverage:
  status:
    project:
      default:
        target: 80%

# flags:
#   unittests:
#     carryforward: false
#     paths:
#       - ./azure_functions_worker

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: no       # [yes :: must have a head report to post]