jobs:
  - job: "Aggregate"
    displayName: 'Aggregate Python Library Workers'

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
  
    templateContext:
      outputParentDirectory: $(Build.ArtifactStagingDirectory)
      outputs:
        - output: pipelineArtifact
          targetPath: $(Build.SourcesDirectory)/final_package
          artifactName: "dist"

    steps:
      # Add download task for each artifact
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Python Worker Artifact'
        inputs:
          buildType: specific
          project: 'internal'
          definition: 652
          buildVersionToDownload: specific
          pipelineId: $(BuildId1)
          artifactName: 'azure-functions-runtime-py313'
          targetPath: "azure-functions-runtime-py313"
      # Compiles the python packages
      - script: |
          mkdir -p $(Build.SourcesDirectory)/final_package
          cp $(Build.SourcesDirectory)/azure-functions-runtime-py3*/*.whl $(Build.SourcesDirectory)/final_package/
        displayName: 'Merge and Compile Python Packages'
      - script: |
          echo "Contents of final_package folder:"
          ls -al $(Build.SourcesDirectory)/final_package
        displayName: 'Verify folder contents post compilation'