parameters:
  PROJECT_NAME: ''

jobs:
  - job: "Build"
    displayName: 'Build Python V2 Library'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux
    
    strategy:
      matrix:
        directory:
          PROJECT_DIRECTORY: 'azure_functions_worker_v2'
    
    templateContext:
      outputParentDirectory: $(Build.ArtifactStagingDirectory)
      outputs:
        - output: pipelineArtifact
          targetPath: $(Build.SourcesDirectory)
          artifactName: "azure-functions-runtime"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.13"
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m pip install -U pip
          python -m pip install build
          cd $(PROJECT_DIRECTORY)
          python -m build
        displayName: 'Build ${{ parameters.PROJECT_NAME }}'
      - bash: |
          pip install pip-audit
          cd $(PROJECT_DIRECTORY)
          pip-audit .
        displayName: 'Run vulnerability scan'