jobs:
  - job: "TestPython"
    displayName: "Run Python Core Tools E2E Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
    
    steps:
    - task: UsePythonVersion@0
      displayName: 'Install Python'
      inputs:
        versionSpec: "3.10"
        addToPath: true
    - task: UseDotNet@2
      displayName: 'Install DotNet 3'
      inputs:
        packageType: 'sdk'
        version: "3.1.x"
    - task: UseDotNet@2
      displayName: 'Install DotNet 6'
      inputs:
        packageType: 'sdk'
        version: "6.x"
    - pwsh: '$(Build.SourcesDirectory)/.ci/e2e_integration_test/start-e2e.ps1'
      env:
        AzureWebJobsStorage: $(LinuxStorageConnectionString311)
        AzureWebJobsCosmosDBConnectionString: $(LinuxCosmosDBConnectionString311)
        AzureWebJobsEventHubConnectionString: $(LinuxEventHubConnectionString311)
        AzureWebJobsServiceBusConnectionString: $(LinuxServiceBusConnectionString311)
        AzureWebJobsSqlConnectionString: $(LinuxSqlConnectionString311)
        AzureWebJobsEventGridTopicUri: $(LinuxEventGridTopicUriString311)
        AzureWebJobsEventGridConnectionKey: $(LinuxEventGridConnectionKeyString311)
      displayName: 'Running Python Language Worker E2E Tests'
