parameters:
  PROJECT_DIRECTORY: 'workers'

jobs:
  - job: "TestPython"
    displayName: "Run Python Docker Custom Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-24.04-min
      os: linux
    
    steps:
      - task: PipAuthenticate@1
        displayName: 'Pip Authenticate'
        inputs:
          artifactFeeds: 'internal/PythonWorker_Internal_PublicPackages'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(CUSTOM_PYTHON_VERSION)
      - bash: |
          chmod +x eng/scripts/install-dependencies.sh

          eng/scripts/install-dependencies.sh $(PYTHON_VERSION) ${{ parameters.PROJECT_DIRECTORY }}
          cd ${{ parameters.PROJECT_DIRECTORY }}/tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install dependencies'
      - bash: |
             python -m pytest --reruns 4 -vv --instafail tests/endtoend
        env:
          DEDICATED_DOCKER_TEST: $(CUSTOM_DED_IMAGE)
          IMAGE_NAME: $(CUSTOM_IMAGE_NAME)
          AzureWebJobsStorage: $(LinuxStorageConnectionString311)
          AzureWebJobsCosmosDBConnectionString: $(LinuxCosmosDBConnectionString311)
          AzureWebJobsEventHubConnectionString: $(LinuxEventHubConnectionString311)
          AzureWebJobsServiceBusConnectionString: $(LinuxServiceBusConnectionString311)
          AzureWebJobsSqlConnectionString: $(LinuxSqlConnectionString311)
          AzureWebJobsEventGridTopicUri: $(LinuxEventGridTopicUriString311)
          AzureWebJobsEventGridConnectionKey: $(LinuxEventGridConnectionKeyString311)
        workingDirectory: $(Build.SourcesDirectory)/${{ parameters.PROJECT_DIRECTORY }}
        displayName: "Running Python DockerCustom tests"