jobs:
  - job: "TestPython"
    displayName: "Run Python Docker Consumption Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
    
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python -m pip install -U -e .[dev]
          python -m pip install --pre -U -e .[test-http-v2]
          if [[ $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi
          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install dependencies'
      - bash: |
             python -m pytest --reruns 4 -vv --instafail tests/endtoend tests/extension_tests/deferred_bindings_tests tests/extension_tests/http_v2_tests
        env:
          CONSUMPTION_DOCKER_TEST: "true"
          AzureWebJobsStorage: $(STORAGE_CONNECTION)
          AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
          AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
          AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
          AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
          AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
          AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
        displayName: "Running $(PYTHON_VERSION) Docker Consumption tests"