jobs:
  - job: "TestPython"
    displayName: "Run Python E2E Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        python-37-fwpc:
          PYTHON_VERSION: '3.7'
          SIMPLIFIED_PYTHON_VERSION: '37'
          TEST_TYPE: 'fwpc-e2e-tests'
        python-37-e2e:
          PYTHON_VERSION: '3.7'
          SIMPLIFIED_PYTHON_VERSION: '37'
          TEST_TYPE: 'e2e-tests'
        python-37-deferred-bindings:
          PYTHON_VERSION: '3.7'
          SIMPLIFIED_PYTHON_VERSION: '37'
          TEST_TYPE: 'deferred-bindings-e2e-tests'
        python-38-fwpc:
          PYTHON_VERSION: '3.8'
          SIMPLIFIED_PYTHON_VERSION: '38'
          TEST_TYPE: 'fwpc-e2e-tests'
        python-38-e2e:
          PYTHON_VERSION: '3.8'
          SIMPLIFIED_PYTHON_VERSION: '38'
          TEST_TYPE: 'e2e-tests'
        python-38-deferred-bindings:
          PYTHON_VERSION: '3.8'
          SIMPLIFIED_PYTHON_VERSION: '38'
          TEST_TYPE: 'deferred-bindings-e2e-tests'
        python-39-fwpc:
          PYTHON_VERSION: '3.9'
          SIMPLIFIED_PYTHON_VERSION: '39'
          TEST_TYPE: 'fwpc-e2e-tests'
        python-39-e2e:
          PYTHON_VERSION: '3.9'
          SIMPLIFIED_PYTHON_VERSION: '39'
          TEST_TYPE: 'e2e-tests'
        python-39-deferred-bindings:
          PYTHON_VERSION: '3.9'
          SIMPLIFIED_PYTHON_VERSION: '39'
          TEST_TYPE: 'deferred-bindings-e2e-tests'
        python-310-fwpc:
          PYTHON_VERSION: '3.10'
          SIMPLIFIED_PYTHON_VERSION: '310'
          TEST_TYPE: 'fwpc-e2e-tests'
        python-310-e2e:
          PYTHON_VERSION: '3.10'
          SIMPLIFIED_PYTHON_VERSION: '310'
          TEST_TYPE: 'e2e-tests'
        python-310-deferred-bindings:
          PYTHON_VERSION: '3.10'
          SIMPLIFIED_PYTHON_VERSION: '310'
          TEST_TYPE: 'deferred-bindings-e2e-tests'
        python-311-fwpc:
          PYTHON_VERSION: '3.11'
          SIMPLIFIED_PYTHON_VERSION: '311'
          TEST_TYPE: 'fwpc-e2e-tests'
        python-311-e2e:
          PYTHON_VERSION: '3.11'
          SIMPLIFIED_PYTHON_VERSION: '311'
          TEST_TYPE: 'e2e-tests'
        python-311-deferred-bindings:
          PYTHON_VERSION: '3.11'
          SIMPLIFIED_PYTHON_VERSION: '311'
          TEST_TYPE: 'deferred-bindings-e2e-tests'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - task: UseDotNet@2
        displayName: 'Install .NET 8'
        inputs:
          version: 8.0.x
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U azure-functions --pre
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi
          if [[ $(PYTHON_VERSION) != "3.7" && $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi

          python setup.py build
          python setup.py webhost --branch-name=dev
          python setup.py extension
          mkdir logs
        displayName: 'Install dependencies and the worker'
      - bash: |
          chmod +x .github/Scripts/$(TEST_TYPE).sh
        displayName: 'Grant execute permission'
    
      - bash: |
             .github/Scripts/$(TEST_TYPE).sh
        env:
          AzureWebJobsStorage: $(LinuxStorageConnectionString$(SIMPLIFIED_PYTHON_VERSION)))
          AzureWebJobsCosmosDBConnectionString: $(LinuxCosmosDBConnectionString$(SIMPLIFIED_PYTHON_VERSION))
          AzureWebJobsEventHubConnectionString: $(LinuxEventHubConnectionString$(SIMPLIFIED_PYTHON_VERSION))
          AzureWebJobsServiceBusConnectionString: $(LinuxServiceBusConnectionString$(SIMPLIFIED_PYTHON_VERSION))
          AzureWebJobsSqlConnectionString: $(LinuxSqlConnectionString$(SIMPLIFIED_PYTHON_VERSION))
          AzureWebJobsEventGridTopicUri: $(LinuxEventGridTopicUriString$(SIMPLIFIED_PYTHON_VERSION))
          AzureWebJobsEventGridConnectionKey: $(LinuxEventGridConnectionKeyString$(SIMPLIFIED_PYTHON_VERSION))
        displayName: "Running $(PYTHON_VERSION) $(TEST_TYPE) tests"
