jobs:
  - job: "TestPython"
    displayName: "Run Python E2E Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString37)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString37)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString37)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString37)
          SQL_CONNECTION: $(LinuxSqlConnectionString37)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString37)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString37)
        Python38:
          PYTHON_VERSION: '3.8'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString38)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString38)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString38)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString38)
          SQL_CONNECTION: $(LinuxSqlConnectionString38)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString38)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString38)
        Python39:
          PYTHON_VERSION: '3.9'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString39)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString39)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString39)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString39)
          SQL_CONNECTION: $(LinuxSqlConnectionString39)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString39)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString39)
        Python310:
          PYTHON_VERSION: '3.10'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString310)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString310)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString310)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString310)
          SQL_CONNECTION: $(LinuxSqlConnectionString310)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString310)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString310)
        Python311:
          PYTHON_VERSION: '3.11'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString311)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString311)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString311)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString311)
          SQL_CONNECTION: $(LinuxSqlConnectionString311)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString311)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString311)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - task: UseDotNet@2
        displayName: 'Install .NET 8'
        inputs:
          version: 8.0.x
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U azure-functions --pre
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi
          if [[ $(PYTHON_VERSION) != "3.7" && $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi

          python setup.py build
          python setup.py webhost --branch-name=dev
          python setup.py extension
          mkdir logs
        displayName: 'Install dependencies and the worker'
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend tests/extension_tests/deferred_bindings_tests tests/extension_tests/http_v2_tests
        env:
          AzureWebJobsStorage: $(STORAGE_CONNECTION)
          AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
          AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
          AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
          AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
          AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
          AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
        displayName: "Running $(PYTHON_VERSION) Python E2E Tests"
