jobs:
  - job: "TestPython"
    displayName: "Run Python Linux Consumption Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
    
    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
        Python38:
          PYTHON_VERSION: '3.8'
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'
        Python311:
          PYTHON_VERSION: '3.11'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U -e .[dev]

          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install dependencies and the worker'
        condition: and(eq(variables.isSdkRelease, false), eq(variables.isExtensionsRelease, false), eq(variables['USETESTPYTHONSDK'], false), eq(variables['USETESTPYTHONEXTENSIONS'], false))
      - bash: |
             python -m pytest -n auto --dist loadfile -vv  --reruns 4 --instafail tests/consumption_tests
        env:
          AzureWebJobsStorage: $(LinuxStorageConnectionString312)
          _DUMMY_CONT_KEY: $(_DUMMY_CONT_KEY)
        displayName: "Running $(PYTHON_VERSION) Linux Consumption tests"
        condition: and(eq(variables.isSdkRelease, false), eq(variables.isExtensionsRelease, false), eq(variables['USETESTPYTHONSDK'], false), eq(variables['USETESTPYTHONEXTENSIONS'], false))