jobs:
  - job: "TestPython"
    displayName: "Run Python Linux Consumption Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
    
    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString37)
        Python38:
          PYTHON_VERSION: '3.8'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString38)
        Python39:
          PYTHON_VERSION: '3.9'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString39)
        Python310:
          PYTHON_VERSION: '3.10'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString310)
        Python311:
          PYTHON_VERSION: '3.11'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString311)
    
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U azure-functions --pre
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi

          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install dependencies and the worker'
      - bash: |
             python -m pytest -n auto --dist loadfile -vv  --reruns 4 --instafail tests/consumption_tests
        env:
          AzureWebJobsStorage: $(STORAGE_CONNECTION)
          _DUMMY_CONT_KEY: $(_DUMMY_CONT_KEY)
        displayName: "Running $(PYTHON_VERSION) Linux Consumption tests"