jobs:
  - job: "TestPython"
    displayName: "Run Python Linux Consumption Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
    
    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString37)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString37)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString37)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString37)
          SQL_CONNECTION: $(LinuxSqlConnectionString37)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString37)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString37)
        Python38:
          PYTHON_VERSION: '3.8'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString38)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString38)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString38)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString38)
          SQL_CONNECTION: $(LinuxSqlConnectionString38)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString38)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString38)
        Python39:
          PYTHON_VERSION: '3.9'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString39)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString39)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString39)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString39)
          SQL_CONNECTION: $(LinuxSqlConnectionString39)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString39)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString39)
        Python310:
          PYTHON_VERSION: '3.10'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString310)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString310)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString310)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString310)
          SQL_CONNECTION: $(LinuxSqlConnectionString310)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString310)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString310)
        Python311:
          PYTHON_VERSION: '3.11'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString311)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString311)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString311)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString311)
          SQL_CONNECTION: $(LinuxSqlConnectionString311)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString311)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString311)

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U azure-functions --pre
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi
          if [[ $(PYTHON_VERSION) != "3.7" && $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi

          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install dependencies and the worker'
        condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/sdk/*'), ne(variables['Build.SourceBranch'], 'refs/heads/extensions/*'))
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Python SDK Artifact'
        inputs:
          buildType: specific
          artifactName: 'azure-functions'
          project: 'internal'
          definition: 679
          buildVersionToDownload: latest
          targetPath: '$(Pipeline.Workspace)/PythonSdkArtifact'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/sdk/*')
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -e $(Pipeline.Workspace)/PythonSdkArtifact
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi
          if [[ $(PYTHON_VERSION) != "3.7" && $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi

          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install test python sdk, dependencies and the worker'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/sdk/*')
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Python Extension Artifact'
        inputs:
          buildType: specific
          artifactName: $(PYTHONEXTENSIONNAME)
          project: 'internal'
          definition: 798
          buildVersionToDownload: latest
          targetPath: '$(Pipeline.Workspace)/PythonExtensionArtifact'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/extensions/*')
      - bash: |
          python -m pip install --upgrade pip

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install -e $(Pipeline.Workspace)/PythonExtensionArtifact
             python -m pip install --pre -U -e .[test-http-v2]
          fi
          if [[ $(PYTHON_VERSION) != "3.7" && $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install -e $(Pipeline.Workspace)/PythonExtensionArtifact
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi
          
          python -m pip install -U -e .[dev]

          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install test python extension, dependencies and the worker'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/extensions/*')
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U azure-functions --pre
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi

          cd tests
          python -m invoke -c test_setup build-protos
        displayName: 'Install dependencies and the worker'
      - bash: |
             python -m pytest -n auto --dist loadfile -vv  --reruns 4 --instafail tests/consumption_tests
        env:
          AzureWebJobsStorage: $(STORAGE_CONNECTION)
          _DUMMY_CONT_KEY: $(_DUMMY_CONT_KEY)
        displayName: "Running $(PYTHON_VERSION) Linux Consumption tests"