parameters:
  PROJECT_DIRECTORY: 'workers'

jobs:
  - job: "TestPython"
    displayName: "Run HTTP Trigger Integration Test"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'
        Python311:
          PYTHON_VERSION: '3.11'
        Python312:
          PYTHON_VERSION: '3.12'
        Python313:
          PYTHON_VERSION: '3.13'
        Python314:
          PYTHON_VERSION: '3.14'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - task: UseDotNet@2
        displayName: 'Install .NET 8'
        inputs:
          version: 8.0.x
      - bash: |
          cd workers
          python -m pip install --upgrade pip
          python -m pip install . pytest~=7.4.4 invoke requests

          # Remove from virtual environment
          pip uninstall -y azure-functions-worker
          pip uninstall -y proxy-worker

          cd ..
          chmod +x eng/scripts/test-setup.sh
          eng/scripts/test-setup.sh
        displayName: 'Install only worker dependencies and build the host'
      - bash: |
             python -m pytest tests/endtoend/test_basic_http_functions.py
        env:
          AzureWebJobsStorage: $(LinuxStorageConnectionString312)
          PYAZURE_WEBHOST_DEBUG: true
        displayName: "Running $(PYTHON_VERSION) Python Simple E2E Tests"
        workingDirectory: $(Build.SourcesDirectory)/${{ parameters.PROJECT_DIRECTORY }}
