jobs:
  - job: "Build"
    displayName: 'Build Python Runtime SDK'

    strategy:
      matrix:
        Python313:
          PYTHON_VERSION: '3.13'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m pip install -U pip
          python -m pip install build
          python -m build
        displayName: 'Build Python RuntimeSDK for $(PYTHON_VERSION)'
      - bash: |
          pip install pip-audit
          pip-audit .
        displayName: 'Run vulnerability scan'