parameters:
  PYTHON_VERSION: ''
  PROJECT_NAME: ''
  PROJECT_DIRECTORY: ''

jobs:
  - job: "Build"
    displayName: 'Build'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux

    steps:
      - template: /eng/templates/shared/build-steps.yml@self
        parameters:
          PYTHON_VERSION: ${{ parameters.PYTHON_VERSION }}
          PROJECT_NAME: ${{ parameters.PROJECT_NAME }}
          PROJECT_DIRECTORY: ${{ parameters.PROJECT_DIRECTORY }}