jobs:
  - job: "Build"
    displayName: 'Build python worker'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.11"
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m venv .env
          .env\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          python -m pip install .
        displayName: 'Build python worker'
        condition: and(eq(variables.isSdkRelease, false), eq(variables.isExtensionsRelease, false), eq(variables['USETESTPYTHONSDK'], false), eq(variables['USETESTPYTHONEXTENSIONS'], false))