jobs:
  - job: "Build"
    displayName: 'Build python worker'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.11"
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m venv .env
          .env\Scripts\Activate.ps1
          python -m pip install --upgrade pip==23.0
          python -m pip install .
        displayName: 'Build python worker'