jobs:
  - job: "Build"
    displayName: 'Build python worker'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux

    variables:
      # Extract the version number from the branch name
      pythonVersion: $[substring(variables['Build.SourceBranchName'], 4, 2)]  # Extract last two digits from dev-xxx

    steps:
      - script: |
          echo "Branch name: $(Build.SourceBranchName)"
          # Extract the last two digits (minor version) from the branch name
          version=$(echo $(Build.SourceBranchName) | sed 's/dev-\([0-9]*\)/\1/')
          minor_version=${version: -2}  # Get last two digits
          echo "Extracted minor version: $minor_version"
          echo "##vso[task.setvariable variable=pythonVersion]$minor_version"
        displayName: 'Extract Python version from branch name'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.$(pythonVersion)'
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
        displayName: 'Build python worker'
      - bash: |
          pip install pip-audit
          pip-audit -r requirements.txt
        displayName: 'Run vulnerability scan'