parameters:
  PROJECT_DIRECTORY: 'workers'

jobs:
  - job: "TestPython"
    displayName: "Run Dependency Checks"

    pool:
      name: ${{ parameters.PoolName }}
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'
        Python311:
          PYTHON_VERSION: '3.11'
        Python312:
          PYTHON_VERSION: '3.12'
        Python313:
          PYTHON_VERSION: '3.13'
        Python314:
          PYTHON_VERSION: '3.14'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - bash: |
          cd workers
          pip install --no-deps .

          PY_VER="$(PYTHON_VERSION)"
          echo "Python version: $PY_VER"

          # Extract minor version
          PY_MINOR="${PY_VER#*.}" 

          if [ "$PY_MINOR" -ge 13 ]; then
              python -c "import pkgutil, sys;
              import proxy_worker;
              print('OK: imports resolved')"
          else
              python -c "import pkgutil, sys;
              import azure_functions_worker;
              print('OK: imports resolved')"
          fi
        displayName: 'Python Worker: check for missing dependencies'
      - bash: |
          cd runtimes/v1
          pip install --no-deps .

          PY_VER="$(PYTHON_VERSION)"
          echo "Python version: $PY_VER"

          # Extract minor version
          PY_MINOR="${PY_VER#*.}"

          if [ "$PY_MINOR" -ge 13 ]; then
              python -c "import pkgutil, sys;
              import azure_functions_runtime_v1;
              print('OK: imports resolved')"
          fi
        displayName: 'Python Library V1: check for missing dependencies'
      - bash: |
          cd runtimes/v2
          pip install --no-deps .

          PY_VER="$(PYTHON_VERSION)"
          echo "Python version: $PY_VER"

          # Extract minor version
          PY_MINOR="${PY_VER#*.}" 

          if [ "$PY_MINOR" -ge 13 ]; then
              python -c "import pkgutil, sys;
              import azure_functions_runtime;
              print('OK: imports resolved')"
          fi
        displayName: 'Python Library V2: check for missing dependencies'
