jobs:
  - job: "TestPython"
    displayName: "Run Python E2E Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        Python312:
          PYTHON_VERSION: '3.13'
          STORAGE_CONNECTION: $(LinuxStorageConnectionString312)
          COSMOSDB_CONNECTION: $(LinuxCosmosDBConnectionString312)
          EVENTHUB_CONNECTION: $(LinuxEventHubConnectionString312)
          SERVICEBUS_CONNECTION: $(LinuxServiceBusConnectionString312)
          SQL_CONNECTION: $(LinuxSqlConnectionString312)
          EVENTGRID_URI: $(LinuxEventGridTopicUriString312)
          EVENTGRID_CONNECTION: $(LinuxEventGridConnectionKeyString312)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - task: UseDotNet@2
        displayName: 'Install .NET 8'
        inputs:
          version: 8.0.x
      - bash: |
          chmod +x eng/scripts/install-dependencies.sh
          chmod +x eng/scripts/test-setup.sh
          
          eng/scripts/install-dependencies.sh $(PYTHON_VERSION)
          eng/scripts/test-setup.sh
        displayName: 'Install dependencies and the worker'
        condition: and(eq(variables.isSdkRelease, false), eq(variables.isExtensionsRelease, false), eq(variables['USETESTPYTHONSDK'], false), eq(variables['USETESTPYTHONEXTENSIONS'], false))
      - bash: |
            python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_blueprint_functions.py
        env:
           AzureWebJobsStorage: $(STORAGE_CONNECTION)
           AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
           AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
           AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
           AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
           AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
           AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
           skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Blueprint E2E Tests"
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_cosmosdb_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python CosmosDB E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_dependency_isolation_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Dependency Isolation E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_durable_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Durable E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_eventgrid_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python EventGrid E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_file_name_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python FileName E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_http_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python HTTP E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_retry_policy_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Retry Policy E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_sql_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python SQL E2E Tests"
        condition: always()
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_third_party_http_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Third Party HTTP E2E Tests"
        condition: always()
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_threadpool_thread_count_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python ThreadPool Thread Count E2E Tests"
        condition: always()
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_timer_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Timer E2E Tests"
        condition: always()
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_warmup_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Warmup E2E Tests"
        condition: always()
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_worker_process_count_functions.py
        env:
             AzureWebJobsStorage: $(STORAGE_CONNECTION)
             AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
             AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
             AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
             AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
             AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
             AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
             skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Worker Process Count E2E Tests"
        condition: always()
      - bash: |
           python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/endtoend/test_worker_process_count_functions.py
        env:
           AzureWebJobsStorage: $(STORAGE_CONNECTION)
           AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
           AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
           AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
           AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
           AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
           AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
           skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Worker Process Count E2E Tests"
        condition: always()
      - bash: |
          python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/extension_tests/http_v2_tests
        env:
          AzureWebJobsStorage: $(STORAGE_CONNECTION)
          AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
          AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
          AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
          AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
          AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
          AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
          skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Worker Http v2 Tests"
        condition: always()
      - bash: |
          python -m pytest -q -n auto --dist loadfile --reruns 4 --cov=./azure_functions_worker --cov-report xml --cov-branch --cov-append tests/extension_tests/deferred_bindings_tests
        env:
          AzureWebJobsStorage: $(STORAGE_CONNECTION)
          AzureWebJobsCosmosDBConnectionString: $(COSMOSDB_CONNECTION)
          AzureWebJobsEventHubConnectionString: $(EVENTHUB_CONNECTION)
          AzureWebJobsServiceBusConnectionString: $(SERVICEBUS_CONNECTION)
          AzureWebJobsSqlConnectionString: $(SQL_CONNECTION)
          AzureWebJobsEventGridTopicUri: $(EVENTGRID_URI)
          AzureWebJobsEventGridConnectionKey: $(EVENTGRID_CONNECTION)
          skipTest: $(skipTest)
        displayName: "Running $(PYTHON_VERSION) Python Worker DB Tests"
        condition: always()
