jobs:
  - job: "TestPython"
    displayName: "Run Python Emulator Tests"

    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
        Python38:
          PYTHON_VERSION: '3.8'
        Python39:
          PYTHON_VERSION: '3.9'
        Python310:
          PYTHON_VERSION: '3.10'
        Python311:
          PYTHON_VERSION: '3.11'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - task: UseDotNet@2
        displayName: 'Install .NET 8'
        inputs:
          version: 8.0.x
      - bash: |
          python -m pip install --upgrade pip
          python -m pip install -U azure-functions --pre
          python -m pip install -U -e .[dev]

          if [[ $(PYTHON_VERSION) != "3.7" ]]; then
             python -m pip install --pre -U -e .[test-http-v2]
          fi
          if [[ $(PYTHON_VERSION) != "3.7" && $(PYTHON_VERSION) != "3.8" ]]; then
              python -m pip install --pre -U -e .[test-deferred-bindings]
          fi

          python setup.py build
        displayName: 'Install dependencies and the worker'
      - bash: |
          sudo npm install -g azurite
          sudo mkdir azurite
          sudo azurite --silent --location azurite --debug azurite\debug.log &
        displayName: 'Install and Run Azurite'
      - bash: |
             python -m pytest -q -n auto --dist loadfile --reruns 4 tests/endtoend/test_blob_functions.py
        env:
          AzureWebJobsStorage: "UseDevelopmentStorage=true"
        displayName: "Running $(PYTHON_VERSION) Python E2E Tests"
