parameters:
  PYTHON_VERSION: ''
  SIMPLE_VERSION: ''
  PROJECT_NAME: ''
  PROJECT_DIRECTORY: 'workers/r2p2'
  CARGO_CONFIG_FILE: 'workers/r2p2/.cargo/config.toml'

jobs:
  - job: "RustBuild${{ parameters.SIMPLE_VERSION }}"
    displayName: 'Build ${{ parameters.PROJECT_NAME }}'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-24.04-min
      os: linux

    steps:
      - template: /eng/templates/shared/r2p2-build-steps.yml@self
        parameters:
          PYTHON_VERSION: ${{ parameters.PYTHON_VERSION }}
          PROJECT_NAME: ${{ parameters.PROJECT_NAME }}
          PROJECT_DIRECTORY: ${{ parameters.PROJECT_DIRECTORY }}
          CARGO_CONFIG_FILE: ${{ parameters.CARGO_CONFIG_FILE }}
