parameters:
  PYTHON_VERSION: ''
  SIMPLE_VERSION: ''
  PROJECT_NAME: ''
  PROJECT_DIRECTORY: 'workers/rust_worker'

jobs:
  - job: "RustBuild${{ parameters.SIMPLE_VERSION }}"
    displayName: 'Build & Test ${{ parameters.PROJECT_NAME }}'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux

    steps:
      - template: /eng/templates/shared/rust-build-steps.yml@self
        parameters:
          PYTHON_VERSION: ${{ parameters.PYTHON_VERSION }}
          PROJECT_NAME: ${{ parameters.PROJECT_NAME }}
          PROJECT_DIRECTORY: ${{ parameters.PROJECT_DIRECTORY }}
