trigger:
  branches:
    include:
      - 1.x-v1
      - v1-runtime-release/*

resources:
  repositories:
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: /ci/variables/cfs.yml@eng

extends:
  template: /ci/code-mirror.yml@eng