trigger:
  batch: true
  branches:
    include:
      - dev
      - release/* # proxy worker releases
      - release-v1/* # V1 worker releases
      - release-v2/* # V2 worker releases

# CI only, does not trigger on PRs.
pr: none

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - dev
    always: true

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: /eng/templates/utils/variables.yml@self
  - template: /eng/templates/utils/official-variables.yml@self
  - name: codeql.excludePathPatterns
    value: deps/,build/

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeSignValidation:
        enabled: true
        break: true

    stages:
       # Python Worker Build and Test Stages
      - stage: BuildPythonWorker
        jobs:
          - template: /eng/templates/official/jobs/build-artifacts.yml@self
      - stage: RunWorkerE2ETests
        dependsOn: BuildPythonWorker
        jobs:
          - template: /eng/templates/official/jobs/ci-e2e-tests.yml@self
      - stage: RunWorkerEmulatorTests
        dependsOn: BuildPythonWorker
        jobs:
          - template: /eng/templates/jobs/ci-emulator-tests.yml@self
            parameters:
              PoolName: 1es-pool-azfunc
      - stage: RunWorkerUnitTests
        dependsOn: BuildPythonWorker
        jobs:
          - template: /eng/templates/jobs/ci-unit-tests.yml@self
      - stage: RunWorkerDockerConsumptionTests
        dependsOn: BuildPythonWorker
        jobs:
          - template: /eng/templates/official/jobs/ci-docker-consumption-tests.yml@self
      - stage: RunWorkerDockerDedicatedTests
        dependsOn: BuildPythonWorker
        jobs:
          - template: /eng/templates/official/jobs/ci-docker-dedicated-tests.yml@self
      - stage: RunWorkerLinuxConsumptionTests
        dependsOn: BuildPythonWorker
        jobs:
          - template: /eng/templates/official/jobs/ci-lc-tests.yml@self

      # Python V2 Library Build and Test Stages
      - stage: BuildV2Library
        dependsOn: []
        jobs:
          - template: /eng/templates/official/jobs/build-library.yml@self
            parameters:
              PROJECT_NAME: 'Python V2 Library'
              PROJECT_DIRECTORY: 'azure_functions_worker_v2'
              ARTIFACT_NAME: 'azure-functions-runtime'
      - stage: RunV2LibraryUnitTests
        dependsOn: BuildV2Library
        jobs:
          - template: /eng/templates/jobs/ci-library-unit-tests.yml@self
            parameters:
              PROJECT_NAME: 'Python V2 Library'
              PROJECT_DIRECTORY: 'azure_functions_worker_v2'

      # Python V1 Library Build and Test Stages
      - stage: BuildV1Library
        dependsOn: []
        jobs:
          - template: /eng/templates/official/jobs/build-library.yml@self
            parameters:
              PROJECT_NAME: 'Python V1 Library'
              PROJECT_DIRECTORY: 'azure_functions_worker_v1'
              ARTIFACT_NAME: 'azure-functions-runtime-v1'
      - stage: RunV1LibraryUnitTests
        dependsOn: BuildV1Library
        jobs:
          - template: /eng/templates/jobs/ci-library-unit-tests.yml@self
            parameters:
              PROJECT_NAME: 'Python V1 Library'
              PROJECT_DIRECTORY: 'azure_functions_worker_v1'