trigger:
  batch: true
  branches:
    include:
    - dev

pr:
  branches:
    include:
    - dev

schedules:
- cron: '0 0 * * MON'
  displayName: At 12:00 AM, only on Monday
  branches:
    include:
      - dev
  always: true

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Build
      jobs:
      - template: /eng/templates/jobs/build.yml@self
    - stage: RunUnitTests
      dependsOn: Build
      jobs:
        - template: /eng/templates/jobs/ci-unit-tests.yml@self