trigger:
  batch: true
  branches:
    include:
    - dev
    - sdk/*
    - extensions/*

pr:
  branches:
    include:
    - dev

schedules:
- cron: '0 0 * * MON'
  displayName: At 12:00 AM, only on Monday
  branches:
    include:
      - dev
  always: true

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/templates/utils/variables.yml@self
  - template: /eng/templates/utils/emulator-variables.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    sdl:
      codeql:
        compiled:
          enabled: true # still only runs for default branch
        sourceLanguages: python, powershell
        excludePathPatterns: deps/,build/
        runSourceLanguagesInSourceAnalysis: true

    settings:
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
    # Python Worker Build and Test Stages
    - stage: BuildPythonWorker
      jobs:
      - template: /eng/templates/jobs/build.yml@self
        parameters:
          PYTHON_VERSION: '3.11'
          PROJECT_NAME: 'Azure Functions Python Worker'
          PROJECT_DIRECTORY: 'workers'
      # Skip the build stage for SDK and Extensions release branches. This stage will fail because pyproject.toml contains the updated (and unreleased) library version
      condition: and(eq(variables.isSdkRelease, false), eq(variables.isExtensionsRelease, false), eq(variables['USETESTPYTHONSDK'], false), eq(variables['USETESTPYTHONEXTENSIONS'], false))
    - stage: CheckPythonWorkerDependencies
      dependsOn: BuildPythonWorker
      jobs:
      - template: /eng/templates/jobs/ci-dependency-check.yml@self
        parameters:
          PoolName: 1es-pool-azfunc-public
    - stage: RunWorkerUnitTests
      dependsOn: BuildPythonWorker
      jobs:
        - template: /eng/templates/jobs/ci-unit-tests.yml@self
          parameters:
            PROJECT_DIRECTORY: 'workers'
            PoolName: 1es-pool-azfunc-public
    - stage: RunWorkerEmulatorTests
      dependsOn: BuildPythonWorker
      jobs:
        - template: /eng/templates/jobs/ci-emulator-tests.yml@self
          parameters:
            PoolName: 1es-pool-azfunc-public
    
    # Python V2 Library Build and Test Stages
    - stage: BuildV2Library
      dependsOn: []
      jobs:
        - template: /eng/templates/jobs/build.yml@self
          parameters:
            PYTHON_VERSION: '3.13'
            PROJECT_NAME: 'V2 Library'
            PROJECT_DIRECTORY: 'runtimes/v2'
    - stage: RunV2LibraryUnitTests
      dependsOn: BuildV2Library
      jobs:
        - template: /eng/templates/jobs/ci-library-unit-tests.yml@self
          parameters:
            PROJECT_NAME: 'V2 Library'
            PROJECT_DIRECTORY: 'runtimes/v2'
            PoolName: 1es-pool-azfunc-public



    # Python V1 Library Build and Test Stages
    - stage: BuildV1Library
      dependsOn: []
      jobs:
        - template: /eng/templates/jobs/build.yml@self
          parameters:
            PYTHON_VERSION: '3.13'
            PROJECT_NAME: 'V1 Library'
            PROJECT_DIRECTORY: 'runtimes/v1'
    - stage: RunV1LibraryUnitTests
      dependsOn: BuildV1Library
      jobs:
        - template: /eng/templates/jobs/ci-library-unit-tests.yml@self
          parameters:
            PROJECT_NAME: 'V1 Library'
            PROJECT_DIRECTORY: 'runtimes/v1'
            PoolName: 1es-pool-azfunc-public