# This workflow will run all tests in tests/consumption_tests in Docker using a consumption image
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Consumption E2E tests

on:
  workflow_dispatch:
  push:
    branches: [ dev, master, main, release/* ]
  pull_request:
    branches: [ dev, master, main, release/* ]

jobs:
  build:
    name: "Python Consumption CI Run"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10", "3.11" ]

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -U azure-functions --pre
          python -m pip install -U -e .[dev]
          python setup.py build
      - name: Running 3.7 Tests
        if: matrix.python-version == 3.7
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString37 }}
        run: python -m pytest -n auto --dist loadfile -vv  --reruns 4 --instafail tests/consumption_tests
      - name: Running 3.8 Tests
        if: matrix.python-version == 3.8
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString38 }}
        run: python -m pytest -n auto --dist loadfile -vv  --reruns 4 --instafail tests/consumption_tests
      - name: Running 3.9 Tests
        if: matrix.python-version == 3.9
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString39 }}
        run: python -m pytest -n auto --dist loadfile -vv --reruns 4 --instafail tests/consumption_tests
      - name: Running 3.10 Tests
        if: matrix.python-version == 3.10
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString310 }}
        run: python -m pytest -n auto --dist loadfile -vv --reruns 4 --instafail tests/consumption_tests
      - name: Running 3.11 Tests
        if: matrix.python-version == 3.11
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString311 }}
        run: python -m pytest -n auto --dist loadfile -vv --reruns 4 --instafail tests/consumption_tests
