# This workflow will run all tests in endtoend/tests in a docker container using the latest consumption image

name: CI Docker Consumption tests

on:
  workflow_dispatch:
  schedule:
    # Run everyday at 5 AM CST
    - cron: "0 10 * * *"

jobs:
  build:
    name: "Python Docker CI Run"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
    permissions: read-all
    env:
        CONSUMPTION_DOCKER_TEST: "true"

    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U -e .
          python pip install pytest
          python setup.py build
      - name: Running 3.8 Tests
        if: matrix.python-version == 3.8
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString38 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString38 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString38 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString38 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString38 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString38 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString38 }}
        run: |
          python -m pytest --reruns 4 -vv --instafail tests/endtoend
      - name: Running 3.9 Tests
        if: matrix.python-version == 3.9
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString39 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString39 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString39 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString39 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString39 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString39 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString39 }}
        run: |
          python -m pytest --reruns 4 -vv --instafail tests/endtoend
      - name: Running 3.10 Tests
        if: matrix.python-version == 3.10
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString310 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString310 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString310 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString310 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString310 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString310 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString310 }}
        run: |
          python -m pytest --reruns 4 -vv --instafail tests/endtoend
      - name: Running 3.11 Tests
        if: matrix.python-version == 3.11
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString311 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString311 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString311 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString311 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString311 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString311 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString311 }}
        run: |
          python -m pytest --reruns 4 -vv --instafail tests/endtoend