# This workflow will install Python dependencies and run end to end tests with single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI E2E tests

on:
  workflow_dispatch:
    inputs:
      archive_webhost_logging:
        description: "For debugging purposes, archive test webhost logs"
        required: false
        default: "false"
  push:
    branches: [dev, main, release/*]
  pull_request:
    branches: [dev, main, release/*]
  schedule:
    # Monday to Thursday 3 AM CST build
    # * is a special character in YAML so you have to quote this string
    - cron: "0 8 * * 1,2,3,4"

jobs:
  build:
    name: "Python E2E CI Run"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    permissions: read-all
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Dotnet 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.x"
      - name: Set up Dotnet 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Install dependencies and the worker
        run: |
          retry() {
            local -r -i max_attempts="$1"; shift
            local -r cmd="$@"
            local -i attempt_num=1
            until $cmd
            do
              if (( attempt_num == max_attempts ))
              then
                echo "Attempt $attempt_num failed and there are no more attempts left!"
                return 1
              else
                echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
                sleep 1
              fi
            done
          }

          python -m pip install --upgrade pip
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -U azure-functions --pre
          python -m pip install -U -e .[dev]

          # Retry a couple times to avoid certificate issue
          retry 5 python setup.py build
          retry 5 python setup.py webhost --branch-name=dev
          retry 5 python setup.py extension
          mkdir logs
      - name: Grant execute permission
        run: chmod +x .github/Scripts/e2e-tests.sh
      - name: Running 3.7 Tests
        if: matrix.python-version == 3.7
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString37 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString37 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString37 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString37 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString37 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString37 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString37 }}
          ARCHIVE_WEBHOST_LOGS: ${{ github.event.inputs.archive_webhost_logging }}
        run: .github/Scripts/e2e-tests.sh
      - name: Running 3.8 Tests
        if: matrix.python-version == 3.8
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString38 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString38 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString38 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString38 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString38 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString38 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString38 }}
          ARCHIVE_WEBHOST_LOGS: ${{ github.event.inputs.archive_webhost_logging }}
        run: .github/Scripts/e2e-tests.sh
      - name: Running 3.9 Tests
        if: matrix.python-version == 3.9
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString39 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString39 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString39 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString39 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString39 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString39 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString39 }}
          ARCHIVE_WEBHOST_LOGS: ${{ github.event.inputs.archive_webhost_logging }}
        run: .github/Scripts/e2e-tests.sh
      - name: Running 3.10 Tests
        if: matrix.python-version == 3.10
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString310 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString310 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString310 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString310 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString310 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString310 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString310 }}
          ARCHIVE_WEBHOST_LOGS: ${{ github.event.inputs.archive_webhost_logging }}
        run: .github/Scripts/e2e-tests.sh
      - name: Running 3.11 Tests
        if: matrix.python-version == 3.11
        env:
          AzureWebJobsStorage: ${{ secrets.LinuxStorageConnectionString311 }}
          AzureWebJobsCosmosDBConnectionString: ${{ secrets.LinuxCosmosDBConnectionString311 }}
          AzureWebJobsEventHubConnectionString: ${{ secrets.LinuxEventHubConnectionString311 }}
          AzureWebJobsServiceBusConnectionString: ${{ secrets.LinuxServiceBusConnectionString311 }}
          AzureWebJobsSqlConnectionString: ${{ secrets.LinuxSqlConnectionString311 }}
          AzureWebJobsEventGridTopicUri: ${{ secrets.LinuxEventGridTopicUriString311 }}
          AzureWebJobsEventGridConnectionKey: ${{ secrets.LinuxEventGridConnectionKeyString311 }}
          ARCHIVE_WEBHOST_LOGS: ${{ github.event.inputs.archive_webhost_logging }}
        run: .github/Scripts/e2e-tests.sh
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov # optional
          fail_ci_if_error: false # optional (default = false)
      - name: Publish Logs to Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test WebHost Logs ${{ github.run_id }} ${{ matrix.python-version }}
          path: logs/*.log
          if-no-files-found: ignore
