# This workflow will install Python dependencies and run end to end tests with single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**.md'

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**.md'

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - main
    always: true

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: Build
        displayName: 'Python E2E CI Tests'
        jobs:
          - job: Build
            pool:
              name: 1es-pool-azfunc
              image: 1es-ubuntu-22.04
              os: linux
            steps:
              - task: UseDotNet@2
                displayName: 'Install .NET Core SDK 8'
                inputs:
                version: '8.x'