# This workflow will install Python dependencies and run end to end tests with single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Worker Build

on:
  workflow_dispatch:
  push:
    branches: [ dev, master, main, release/* ]
  pull_request:
    branches: [ dev, master, main, release/* ]

jobs:
  build-python-worker:
    name: "Build Python Worker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        dotnet-version: [ '2.2.207' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup DotNet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies and the worker
      run: |
        python -m pip install -q --upgrade pip
        python -m pip install -q --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -U -e .[dev]
        python -m pip install -q --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -U azure-functions --pre
        python setup.py build
        python setup.py webhost